app/blueprints/shop/models.py
from app import db
from datetime import datetime as dt
from app.blueprints.authentication.models import User

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    image = db.Column(db.String)
    description = db.Column(db.Text)
    price = db.Column(db.Float)
    tax = db.Column(db.Float)
    date_created = db.Column(db.DateTime, default=dt.utcnow)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def to_dict(self):
        data = {
            'id': self.id,
            'name': self.name,
            'description': self.description,
            'price': self.price,
            'tax': self.tax,
            'date_created': self.date_created
        }
        return data

    def from_dict(self, data):
        for attr in ['name', 'description', 'image', 'price']:
            if attr in data:
                setattr(self, attr, data[attr])
        self.tax = round(self.price * .06, 2)

    def __repr__(self):
        return f'<Product: {self.name} @{self.price}>'

    
class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    product_id = db.Column(db.ForeignKey('product.id'), nullable=False)
    date_added = db.Column(db.DateTime, default=dt.utcnow)

    def to_dict(self):
        data = {
            'product': Product.query.get(self.product_id).to_dict(),
            'user': User.query.get(self.user_id).to_dict()
        }
        return data
    
    def save(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'<Cart: {self.user_id}: {self.product_id}>'

class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    product_id = db.Column(db.ForeignKey('product.id'), nullable=False)
    date_filled = db.Column(db.DateTime, default=dt.utcnow)

    def save(self):
        db.session.add(self)
        db.session.commit()

app/blueprints/shop/__init__.py
from flask import Blueprint

bp = Blueprint('shop', __name__, url_prefix='/shop')

from .import models, routes

app/blueprints/shop/routes.py
from flask import render_template, redirect, url_for, current_app as app, flash, request, session, jsonify
from flask_login.utils import login_required
from flask_migrate import current
from . import bp as shop
import stripe
from .models import Product, Cart, Order
from app.seed import seed_data
from flask_login import current_user
import json
from app import db


#print('stripe:', app.config.get('STRIPE_PUBLISHABLE_KEY'))

@shop.context_processor
def get_stripe_data():
    stripe.api_key = app.config.get('STRIPE_SECRET_KEY')
    return { 'stripe': stripe }

stripe.api_key = "sk_test_51IxhpTB4Zc5fMFvYks9440tRdZt7AYiaYzLzT5vTo2HiYbO7Rua4NW4045HoZI2pKmCD4AObVP3kFnO2uw4nwFXR00d6LyTuPu"

@shop.route('/')
def index():
    context = {
        'products': [p.to_dict() for p in Product.query.all()]
    }
    return render_template('shop/index.html', **context)

@shop.route('/seed')
def seed():
    seed_data()
    flash('Your product data has been seeded.', 'primary')
    return redirect(url_for('shop.index'))

@shop.route('/cart/add')
def add_to_cart():
    try:
        p = Product.query.get(request.args.get('product_id'))
        print(current_user.id)
        item = Cart(user_id=current_user.id, product_id=p.id)
        item.save()
        flash(f"{p.name} has been added successfully", 'success')
    except Exception as err:
        flash(f"There was an error adding the {p.name}", 'danger')
        print(err)
    return redirect(url_for('shop.index'))

@shop.route('/cart')
def cart():
    from app.context_processors import build_cart

    display_cart = build_cart()['cart_dict']
    
    session['session_display_cart'] = display_cart
    
    context = {
        'cart': display_cart.values()
    }
    return render_template('shop/cart.html', **context)

@shop.route('/checkout', methods=['POST'])
def checkout():
    dc = session.get('session_display_cart')
    l_items = []
    for product in dc.values():
        product_dict = {
            'price_data': {
                'currency': 'usd',
                'unit_amount': int(float(product['price'])) * 100,
                'product_data': {
                    'name': product['name'],
                    'images': [product['image']],
                },
            },
            'quantity': product['quantity'],
        }
        l_items.append(product_dict)
        
    
    try:
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=l_items,
            mode='payment',
            success_url=app.config.get('YOUR_DOMAIN') + '/shop/success',
            cancel_url=app.config.get('YOUR_DOMAIN') + '/shop/cancel',
        )
        
        for i in Cart.query.filter_by(user_id=current_user.id).all():
            db.session.delete(i)
        db.session.commit()
        print(l_items)
        return jsonify({'session_id': checkout_session.id})
    except Exception as e:
        return jsonify(error=str(e)), 403

@shop.route('/success')
def success():
    # [db.session.delete(c) for c in Cart.query.filter_by(user_id=current_user.id).all()]
    # db.session.commit()
    flash('All items remove from the cart successfully', 'info')
    return render_template('shop/checkout/success.html')

app/templates/shop/cart.html
{% extends 'layout.html' %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/delete-this-cart.css') }}">
{% endblock styles %}

{% block content %}
    <p>This is the Cart Page</p>
    <hr>
        <div class="card shopping-cart">
            <div class="card-header bg-dark text-light">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                Shipping cart
                <a href="{{ url_for('shop.index') }}" class="btn btn-outline-info btn-sm pull-right">Continue shopping</a>
                <div class="clearfix"></div>
            </div>
            <div class="card-body">
                <!-- PRODUCT -->
                {% for p in cart %}
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-2 text-center">
                        <img class="img-responsive" src="http://placehold.it/120x80" alt="prewiew" width="120" height="80">
                    </div>
                    <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                        <h4 class="product-name"><strong>{{ p.name }}</strong></h4>
                        <h4>
                            <small>{{ p.description }}</small>
                        </h4>
                    </div>
                    <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                        <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                            <h6><strong>{{ p.price }}<span class="text-muted">x</span></strong></h6>
                        </div>
                        <div class="col-4 col-sm-4 col-md-4">
                            <div class="quantity">
                                <input type="number" step="1" max="99" min="1" value="{{ p.quantity }}" title="Qty" class="qty" size="4">
                            </div>
                        </div>
                        <div class="col-2 col-sm-2 col-md-2 text-right">
                            <button type="button" class="btn btn-outline-danger btn-xs">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <hr>
                <!-- END PRODUCT -->
                {% endfor %}
                <div class="pull-right">
                    <a href="" class="btn btn-outline-secondary pull-right">
                        Update Shopping cart
                    </a>
                </div>
            </div>
            <div class="card-footer">
                <!-- <div class="coupon col-md-5 col-sm-5 no-padding-left pull-left">
                    <div class="row">
                        <div class="col-6">
                            <input type="text" class="form-control" placeholder="cupone code">
                        </div>
                        <div class="col-6">
                            <input type="submit" class="btn btn-default" value="Use cupone">
                        </div>
                    </div>
                </div> --> 
                <div class="text-right">
                    <div class="cart-totals">
                        Subtotal: <b>${{ "{:,.2f}".format(cart_subtotal) }}</b>
                    </div>
                    <div class="cart-totals">
                        Tax: <b>${{ "{:,.2f}".format(cart_tax) }}</b>
                    </div>
                    <div class="cart-totals">
                        Grand total: <b>${{ "{:,.2f}".format(cart_grandtotal) }}</b>
                    </div>
                </div>
                <div class="pull-right" style="margin: 10px">
                    <form id="checkout-form" action="{{ url_for('shop.checkout') }}" method="POST">
                        <input type="submit" class="btn btn-success pull-right" value="Checkout" />
                    </form>
                </div>
            </div>
        </div>
{% endblock content %}

{% block scripts %}
    {{ super() }}
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>

    <script>
        var stripe = Stripe('{{ STRIPE_PUBLISHABLE_KEY }}')

        $('#checkout-form').on('submit', function (e) {
            e.preventDefault();
            fetch('{{ url_for("shop.checkout") }}', {
                'method': 'POST',
                'mode': 'cors',
                'headers': {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ 'message': 'This works' })
            })
                .then(res => res.json())
                .then(data => stripe.redirectToCheckout({ sessionId: data['session_id'] }))
        })
    </script>
{% endblock scripts %}

app/templates/shop/index.html
{% extends 'layout.html' %}

{% block content %}
    <p>This is the Shop Page.</p>
    <hr>
    <div class="card-deck">
        {% for p in products %}
        <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h6>
                    {{ p.name }} 
                    <span class="float-right">{{ "{:,.2f}".format(p.price) }}</span>
                </h6>
            </div>
            
            <div class="card-body">
                <img class="card-img-top" src="https://www.imagehandler.net/preview/?istyle=0000&fmt=jpg&w=2000&h=2000&cmp=100&c=999&img=A1043138000&iset=0108&iindex=0007" alt="{{ p.name }}">
                <a class="btn btn-success btn-block" href="{{ url_for('shop.add_to_cart', product_id=p.id) }}" style="margin-top: 10px;">Add to cart</a>
                <p class="card-text" style="margin-top: 10px;">{{ p.description }}</p>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>

{% endblock content %}